name: Benchmark

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  benchmark:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        package-size: ['medium']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install hyperfine
        run: |
          sudo apt-get update
          sudo apt-get install -y hyperfine

      - name: Cache dependencies
        run: |
          cd test/${{ matrix.package-size }}-package
          npm install

      - name: Run baseline benchmarks
        run: |
          echo "Benchmarking baseline npm config commands"
          cd test/${{ matrix.package-size }}-package
          hyperfine --warmup 2 --runs 10 "npm install"

      - name: Run Sustainable npm action
        uses: ./

      - name: Run action benchmarks
        run: |
          echo "Benchmarking Sustainable npm config commands"
          cd test/${{ matrix.package-size }}-package
          hyperfine --warmup 2 --runs 10 "npm install"
